{
 "title": "ASN View",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "asn_num", "label": "ASN", "query": "109" }
  ]
 },
 "panels": [
  {
   "title": "Advertised IP Addresses",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  max(timestamp) as time,\n  count(*) as \"ipv4\"\nFROM\n  global_ip_rib\nWHERE\n  recv_origin_as = [[asn_num]]\n  and family(prefix) = 4\nGROUP BY prefix\n"
    },
    {
     "rawSql": "SELECT\n  max(timestamp) as time,\n  count(*) as \"ipv6\"\nFROM\n  global_ip_rib\nWHERE\n  recv_origin_as = [[asn_num]]\n  and family(prefix) = 6\nGROUP BY prefix\n"
    }
   ]
  },
  {
   "title": "Upstream ASNs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(distinct asn_left) as count\n  from as_path_analysis a\n  where a.asn = [[asn_num]]\n"
    }
   ]
  },
  {
   "title": "Originating Prefix Trend",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(interval_time),\n  v4_prefixes,v6_prefixes,v4_with_rpki,v6_with_rpki,v4_with_irr,v6_with_irr\nFROM\n  stats_ip_origins\nWHERE\n  $__timeFilter(interval_time) and asn = [[asn_num]]\nORDER BY interval_time asc\n"
    }
   ]
  },
  {
   "title": "Downstream ASNs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(distinct asn_right) as count\n  from as_path_analysis a\n  where a.asn = [[asn_num]] and asn_right != 0\n"
    }
   ]
  },
  {
   "title": "ASN Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select as_name,org_id,org_name,address,city,state_prov,country,remarks,raw_output,source \n  from info_asn i \n  where asn = [[asn_num]]"
    }
   ]
  },
  {
   "title": "Upstream ASNs",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "select a.asn_left as \"ASN\",max(as_name) as \"Name\",max(org_id) as \"Org Id\",max(org_name) as \"Org Name\",max(city) as \"City\",\n    max(state_prov) as \"State\",max(country) as \"Country\",max(source) as \"Source\"\n  from as_path_analysis a\n      LEFT JOIN info_asn i ON (i.asn = a.asn_left)\n  where a.asn = [[asn_num]] and asn_left != 0\n  group by a.asn_left"
    }
   ]
  },
  {
   "title": "Downstream ASNs",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "rawSql": "select  a.asn_right as \"ASN\",max(as_name) as \"Name\",max(org_id) as \"Org Id\",max(org_name) as \"Org Name\",max(city) as \"City\",\n    max(state_prov) as \"State\",max(country) as \"Country\",max(source) as \"Source\"\n  from as_path_analysis a\n      LEFT JOIN info_asn i ON (i.asn = a.asn_right)\n  where a.asn = [[asn_num]] and asn_right != 0\n  group by a.asn_right"
    }
   ]
  },
  {
   "title": "Advertised Prefixes (multiple shown for all IRR entries)",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT r.prefix as \"Prefix\",g.rpki_origin_as AS \"RPKI Origin AS\",i.origin_as as \"IRR Origin AS\",\"Last Change\", i.descr as \"IRR Description\", i.source as \"IRR Source\"\n\nFROM (\n      select\n        prefix,\n        max(timestamp) as \"Last Change\"\n      FROM global_ip_rib\n      WHERE recv_origin_as = [[asn_num]]\n      GROUP BY prefix\n  ) r\n  LEFT JOIN info_route i ON (i.prefix = r.prefix)\n  LEFT JOIN global_ip_rib g ON (g.prefix = r.prefix)\n\n\n"
    }
   ]
  }
 ]
}